LOGGING_LEVEL: 'INFO'
LOGGING_FORMAT: '%(asctime)-15s | %(levelname)s | %(filename)s | %(lineno)d: %(message)s'

WEB_HOST: '127.0.0.1'
WEB_PORT: 5000

KAFKA_BROKER: "127.0.0.1:9092"
# server response about the product
PRODUCER_DATA_TOPIC: "wb-category"
# information about each product
CONSUMER_DATA_TOPIC: "wb-products"

AUTO_OFFSET_RESET: "earliest"