version: '1'
services:
  worker:
    # Путь до Dockerfile
    build: ./worker
    environment:
      ## Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED=True
      ##
    # Создание переменных окружения в контейнере
    # Перезапускаем сервис в случае падения 
    restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
    volumes:
      - ./worker:/worker
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "2135:5000"
    command: python worker.py
    network_mode: "custom_network_name"
  parser:
    build: ./parser
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=True
    deploy:
      replicas: 3
    command: python parser_products.py
    network_mode: "custom_network_name"
