version: '1'
services:
  worker:
    # Путь до Dockerfile
    build: ./worker
    environment:
      # для отладки (при запуске в релиз убрать!)
      - FLASK_DEBUG=development
      ## Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED=True
      ##
    # Создание переменных окружения в контейнере
    # Перезапускаем сервис в случае падения 
    restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
    volumes:
      - ./worker:/worker
    deploy:
      replicas: 3
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "2135-2137:5000"
    command: python worker.py
    network_mode: "alena_default"
  parser:
    build: ./parser
    restart: on-failure
    command: python parser_products.py
    # network_mode: "alena_default"
