FROM python:3.9-slim-buster

RUN apt-get update
RUN pip install --upgrade pip
RUN pip install requests
RUN pip install confluent_kafka

COPY . D:/python/"getting information about products from wildberries"
WORKDIR D:/python/"getting information about products from wildberries"

CMD ["python", "worker.py"]