KAFKA_BROKER: 'broker:29092' # серевер брокера Kafka с топиками
PRODUCER_DATA_TOPIC: "wb-category" # название категории в kafka, где хранятся товары с данными в виде словаря
CONSUMER_DATA_TOPIC: "wb-products" #  название категории в kafka, где хранятся данные отдельно в виде словаря
