WEB_HOST: '0.0.0.0' # по какому адресу запускается программа и куда надо отправлять категорию wildberries
KAFKA_BROKER: 'broker:29092' # серевер брокера Kafka с топиками
PRODUCER_DATA_TOPIC: "wb-category" # название категории в kafka, где хранятся товары с данными в виде словаря
